### ISSUE TITLE
Update of cache/.htaccess

### ISSUE THREAD

**Issue by crmb** [OddOneOut/bwp-minify#55]
Hello,

I think the value of "Header set Cache-Control "public, max-age=" in the cache/.htaccess file is updated only when you disable&re-enable the "CDN friendly" url. But not when the cache age is updated on the first tab

**Comment by kminh** [comment]
That's true, the `.htaccess` file is not needed when you're not using the CDN friendly url feature. Is the cache age not working for you when not using it?

**Comment by c266** [comment]
Yes i looked into the problem and it seems that with a default apache installation (Etag sent but no Cache-control) Firefox never cache requests with querystring (always GET 200). So i added the Cache-Control headers and now its is working.

**Comment by kminh** [comment]
Something is not right because with or without the CDN friendly feature cache headers should be properly added. Unless you append a cache buster (there's a setting in BWP Minify > General Options), Firefox should cache minified contents correctly, even when the urls contain query variables.

Perhaps you should post a link to one of your minified file here so I can take a look.

**Comment by kminh** [comment]
Closing for now, feel free to repoen if needed.

**Comment by c266** [comment]
Sorry for not giving news. Yes it was an issue with my setup (some misconception about apache cache-control settings)
